server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: goldsilverratio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goldsilverratio?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: iFila5408.
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

app:
  metals: {}
  fred:
    api-key: "743e7fd4a433a831d1f2ce4d69e3a5fa"
